version: "3"

services:
    worker:
        image: 192.168.0.8:5000/worker
        environment:
            - TASK_ADDRESS=tcp://distributor:5000
            - DB_ADDRESS=mysql://root:password@mysql/reinforcement_learning
        deploy:
            replicas: 4
    distributor:
        image: 192.168.0.8:5000/distributor
        environment:
            - TASK_ADDRESS=tcp://*:5000
    mysql:
        image: 192.168.0.8:5000/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - /home/docker/mysql:/var/lib/mysql
        deploy:
            placement:
                constraints:
                    - node.labels.has_sql == true
    myadmin:
        image: 192.168.0.8:5000/phpmyadmin
        environment:
            - PMA_HOST=mysql
        ports:
            - 8080:80
