version: "3"

services:
    worker:
        image: 192.168.0.8:5000/rlworker
        environment:
            - TASK_ADDRESS=distributor:5000
            - RESULT_ADDRESS=receiver:6000
        deploy:
            replicas: 4
    distributor:
        image: 192.168.0.8:5000/rldistributor
        environment:
            - TASK_ADDRESS=*:5000
    receiver:
        image: 192.168.0.8:5000/rlreceiver
        environment:
            - RESULT_ADDRESS=*:6000
    mysql:
        image: 192.168.0.8:5000/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - /home/docker/mysql:/var/lib/mysql
        deploy:
            placement:
                constraints:
                    - node.labels.has_sql == true
