version: '3'

services:
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 3306:3306
        volumes:
            - /home/docker/mysql:/var/lib/mysql
        networks:
            - default
            - swarm
    myadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql 
        ports:
            - 8080:80

networks:
    swarm:
        driver: overlay
