version: "3"

services:
    worker:
        image: 192.168.0.8:5000/worker
        environment:
            - QUEUE_ADDRESS=tcp://distributor:5000
            - DB_ADDRESS=mysql://root:password@mysql/reinforcement_learning
    distributor:
        image: 192.168.0.8:5000/distributor
        environment:
            - QUEUE_ADDRESS=tcp://*:5000
            - DB_ADDRESS=mysql://root:password@mysql/reinforcement_learning
    mysql:
        image: 192.168.0.8:5000/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - /home/docker/mysql:/var/lib/mysql
            
    myadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql 
        ports:
            - 8080:80
