version: "3"

services:
    worker:
        image: 192.168.0.8:5000/worker:test
        environment:
            - QUEUE_ADDRESS=tcp://distributor:5000
            - DB_ADDRESS=mysql://root:password@mysql/reinforcement_learning
        networks:
            - SQL_swarm
    distributor:
        image: 192.168.0.8:5000/distributor
        environment:
            - QUEUE_ADDRESS=tcp://*:5000
            - DB_ADDRESS=mysql://root:password@mysql/reinforcement_learning
        networks:
            - SQL_swarm
networks:
  SQL_swarm:
    external: true
