version: '3.1'

services:
    portainer:
        image: portainer/portainer
        ports:
            - "9000:9000"
        networks:
            - portainer-net
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: 
                    - node.role==manager

volumes:
    portainer_data:
        
networks:
  portainer-net:
