version: '3'

services:
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - default
            - swarm
        deploy:
            placement:
                constraints:
                    - node.hostname == DP00262-1
    myadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        ports:
            - 8080:80

volumes:
    mysql_data:
        external:
            name: mysql_data

networks:
    swarm:
        driver: overlay
