version: '3'

services:
    jupyter:
        image: firefoxmetzger/rlunit-jupyter
        environment:
            - DB_ADDRESS=mysql://root:password@mysql/reinforcement_learning
        entrypoint:
            - start-notebook.sh
            - --NotebookApp.password=sha1:d6612504be77:10364c85161732cca16cb3bf6e6e2fb219ebc0ba
        volumes:
            - jupyter:/home/jovyan/
        ports:
            - "80:8888"
        networks:
            - swarm
        deploy:
            placement:
                constraints:
                    - node.hostname == DP00262-1
volumes:
    jupyter:
        external:
            name: jupyter_data
networks:
    swarm:
        external:
            name: SQL_swarm
