version: '3.1'

services:
    entrypoint:
        image: firefoxmetzger/rlunit-episode-reward-entrypoint
        environment:
            - EXPERIMENT_EVENTS=tcp://hub:1337
            - ENTRYPOINT_ADDRESS=tcp://*:4000
        networks:
            - default
            - swarm
    map:
        image: firefoxmetzger/rlunit-episode-reward-mapper
        environment:
            - ENTRYPOINT_ADDRESS=tcp://entrypoint:4000
            - REDUCER_REQUEST_ADDRESS=tcp://shuffle:5500
            - MAPPER_REPLY_ADDRESS=tcp://shuffle:6000
            - SCHEDULER_ADDRESS=tcp://shuffle:7000
        deploy:
            replicas: 3
    shuffle:
        image: firefoxmetzger/rlunit-episode-reward-shuffle
        environment:
            - REDUCER_REQUEST_ADDRESS_OUT=tcp://*:5500
            - MAPPER_REPLY_ADDRESS_IN=tcp://*:6000
            - SCHEDULER_ADDRESS_IN=tcp://*:7000
            - REDUCER_REQUEST_ADDRESS_IN=tcp://*:5000
            - MAPPER_REPLY_ADDRESS_OUT=tcp://*:6500
            - SCHEDULER_ADDRESS_OUT=tcp://*:8591
    reduce:
        image: firefoxmetzger/rlunit-episode-reward-reducer
        environment:
            - DB_ADDRESS=mysql://root:password@mysql/reinforcement_learning
            - REDUCER_REQUEST_ADDRESS=tcp://shuffle:5000
            - MAPPER_REPLY_ADDRESS=tcp://shuffle:6500
            - SCHEDULER_ADDRESS=tcp://shuffle:8591
            - DROP_DELAY=5
        networks:
            - default
            - swarm

networks:
  default:
  swarm:
    external:
        name: SQL_swarm
